# Generated by Django 4.0.4 on 2022-11-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_driver_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('pswd', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('user_type', models.CharField(default='', max_length=30)),
                ('idproof', models.ImageField(default='', upload_to='pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='pic/')),
                ('name', models.CharField(default='', max_length=30)),
                ('car_number', models.CharField(default='', max_length=50)),
                ('seat', models.CharField(default='', max_length=30)),
                ('specification', models.CharField(default='', max_length=30)),
                ('price', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=30)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_driverBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_email', models.CharField(default='', max_length=30)),
                ('driver_phone', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('fromdate', models.CharField(default='', max_length=30)),
                ('todate', models.CharField(default='', max_length=30)),
                ('hrs', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_email', models.CharField(default='', max_length=30)),
                ('subject', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('reply', models.CharField(default='', max_length=30)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_buyer_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(default='', max_length=250)),
                ('cardnum', models.CharField(default='', max_length=255)),
                ('expiry', models.CharField(default='', max_length=250)),
                ('cvvnum', models.CharField(default='', max_length=250)),
                ('status', models.CharField(default='', max_length=250)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='carRentapp.tbl_user')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='carRentapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_buyer_car_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(default='', max_length=250)),
                ('cardnum', models.CharField(default='', max_length=255)),
                ('expiry', models.CharField(default='', max_length=250)),
                ('cvvnum', models.CharField(default='', max_length=250)),
                ('price', models.IntegerField(default='')),
                ('status', models.CharField(default='', max_length=255)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=30)),
                ('fromdate', models.CharField(default='', max_length=30)),
                ('todate', models.CharField(default='', max_length=30)),
                ('hrs', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('owner_email', models.CharField(default='', max_length=30)),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_product')),
            ],
        ),
    ]
