# Generated by Django 4.0.4 on 2023-01-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default='', max_length=100)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_product')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user')),
            ],
        ),
        migrations.DeleteModel(
            name='Tbl_driver_price',
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='totalprice',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tbl_driverbook',
            name='totalprice',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tbl_buyer_payment',
            name='buyer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRentapp.tbl_user'),
        ),
    ]
