# Generated by Django 4.0.4 on 2023-01-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0002_tbl_review_delete_tbl_driver_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_Review',
        ),
    ]
