# Generated by Django 4.0.4 on 2023-01-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0004_tbl_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_buyer_payment',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
