# Generated by Django 4.0.4 on 2023-01-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0006_alter_tbl_buyer_car_payment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_review',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
