# Generated by Django 4.0.4 on 2023-01-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0009_tbl_buyer_payment_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_buyer_payment',
        ),
    ]
