# Generated by Django 4.0.4 on 2023-01-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0011_tbl_buyer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_driverbook',
            name='driverid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
