# Generated by Django 4.0.4 on 2023-01-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0012_tbl_driverbook_driverid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_driverbook',
            old_name='hrs',
            new_name='day',
        ),
    ]
