# Generated by Django 4.0.4 on 2023-01-07 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0013_rename_hrs_tbl_driverbook_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_buyer_car_payment',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='carRentapp.tbl_user'),
        ),
    ]
