# Generated by Django 4.0.4 on 2023-01-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0014_tbl_buyer_car_payment_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='owner_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
