# Generated by Django 4.0.4 on 2023-01-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0015_tbl_booking_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_booking',
            old_name='hrs',
            new_name='day',
        ),
    ]
