# Generated by Django 4.0.4 on 2023-01-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRentapp', '0016_rename_hrs_tbl_booking_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='tbl_buyer_car_payment',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='tbl_buyer_car_payment',
            name='owner_email',
            field=models.CharField(default='', max_length=250),
        ),
    ]
